/*
 * ============================================================
 * sprite2d.c
 * ============================================================
 * A node that displays a 2D image with adjustable position/rotation/scale -
 * the first node that actually loads and draws real content (unlike Element2D/Element3D
 * which are still skeletal and do not render).
 *
 * Loading is done via the shared embedded_images.h (generated by the exporter
 * at each export, see ps2_exporter.c) - raw pixels (GS_PSM_CT32) are pre-converted
 * at export time (on the development machine, not on the PS2), no compressed formats
 * (PNG/JPEG/...) ever reach the PS2, and there is no runtime filesystem access -
 * the exact same professionally proven manual PS2 workflow (see gsKit_texture_finish
 * used here, same technique as embedding fonts in real PS2 projects). This keeps
 * the executable free of libpng/libjpeg/libtiff entirely - they are not needed.
 *
 * @PS2_EXPORT_LIBS: -L$(GSKIT)/lib -lgskit -lgskit_toolkit -ldmakit
 * @PS2_EXPORT_INCLUDES: -I$(GSKIT)/include
 * ============================================================
 */

#include <string.h>
#include <stdlib.h>
#include <malloc.h>
#include <math.h>

#include <gsKit.h>

#include "node_interface.h"
#include "engine_context.h"
#include "embedded_images.h"

/* gsKit_texture_finish is not declared in any public gsKit header (internal
 * extern only inside gsToolkit.c) - same manual declaration used by any
 * professional PS2 project that uploads a raw texture ready for VRAM directly
 * without decoding any compressed format (instead of relying on gsKit_texture_png/jpeg/...
 * which would pull full external decoding libraries unnecessarily) */
extern int gsKit_texture_finish(GSGLOBAL *gsGlobal, GSTEXTURE *Texture);

/* The real Sprite2D data - this is the structure that instance_size bytes
 * actually allocate when the scene is loaded, and offsetof() below points to
 * its exact fields. texture/texture_loaded are internal state only - not
 * properties editable from the properties panel, so they are not included
 * in the sprite2d_properties or sprite2d_property_offsets arrays below. */
typedef struct {
    float position_x;
    float position_y;
    float rotation;   /* Rotation in radians around image center */
    float scale_x;
    float scale_y;
    const char *image_path; /* Exact same text as in the properties panel - lookup key for embedded_image_find */
    int raw_width;          /* RAW dimensions when using a file without a header */
    int raw_height;
    int raw_format;         /* GS PSM value when using RAW */

    GSTEXTURE texture;
    int texture_loaded; /* 0 = not yet loaded (or image not embedded at all) */
} sprite2d_instance_t;

static void sprite2d_init(void *self) {
    sprite2d_instance_t *inst = (sprite2d_instance_t *)self;
    memset(&inst->texture, 0, sizeof(GSTEXTURE));
    inst->texture_loaded = 0;
}

/* Loads the texture from the image embedded in the executable itself - lazy
 * (on first draw only) to ensure all properties are actually written from the
 * loaded scene before any load attempt */
static void sprite2d_load_texture(sprite2d_instance_t *inst) {
    if (inst->texture_loaded) return;
    if (inst->image_path == NULL || inst->image_path[0] == '\0') return;

    const embedded_image_t *img = embedded_image_find(inst->image_path);
    if (img == NULL) return; /* Not embedded (conversion failed at export, or invalid path) */

    GSGLOBAL *gsGlobal = engine_get_gs_global();

    inst->texture.Width  = img->width;
    inst->texture.Height = img->height;
    inst->texture.PSM    = GS_PSM_CT32;
    inst->texture.Filter = GS_FILTER_LINEAR;

    unsigned int need = gsKit_texture_size_ee(inst->texture.Width, inst->texture.Height, inst->texture.PSM);
    inst->texture.Mem = memalign(128, need);
    if (inst->texture.Mem == NULL) return;

    memcpy(inst->texture.Mem, img->data, need);

    inst->texture_loaded = (gsKit_texture_finish(gsGlobal, &inst->texture) == 0);
}

static void sprite2d_update(void *self, float delta_time) {
    (void)self;
    (void)delta_time;
}

static void sprite2d_draw(void *self) {
    sprite2d_instance_t *inst = (sprite2d_instance_t *)self;

    sprite2d_load_texture(inst);
    if (!inst->texture_loaded) return;

    GSGLOBAL *gsGlobal = engine_get_gs_global();

    float half_w = ((float)inst->texture.Width  * inst->scale_x) / 2.0f;
    float half_h = ((float)inst->texture.Height * inst->scale_y) / 2.0f;

    /* (0,0) is the image center as the editor sees it. We transform the rectangle
     * corners around this center and then use gsKit's official textured quad API
     * instead of approximating or ignoring rotation. Vertex order preserves UV order:
     * top-left, top-right, bottom-left, bottom-right. */
    float c = cosf(inst->rotation);
    float s = sinf(inst->rotation);
    float local_x[4] = { -half_w, half_w, -half_w, half_w };
    float local_y[4] = { -half_h, -half_h, half_h, half_h };
    float x[4], y[4];
    for (int i = 0; i < 4; i++) {
        x[i] = inst->position_x + local_x[i] * c - local_y[i] * s;
        y[i] = inst->position_y + local_x[i] * s + local_y[i] * c;
    }
    gsKit_prim_quad_texture(gsGlobal, &inst->texture,
        x[0], y[0], 0.0f, 0.0f,
        x[1], y[1], (float)inst->texture.Width, 0.0f,
        x[2], y[2], 0.0f, (float)inst->texture.Height,
        x[3], y[3], (float)inst->texture.Width, (float)inst->texture.Height,
        1, GS_SETREG_RGBAQ(0x80, 0x80, 0x80, 0x80, 0x00));
}

static void sprite2d_destroy(void *self) {
    sprite2d_instance_t *inst = (sprite2d_instance_t *)self;
    if (inst->texture.Mem != NULL) {
        free(inst->texture.Mem);
        inst->texture.Mem = NULL;
    }
    /* Note: freeing VRAM itself (inst->texture.Vram) requires gsKit_vram_clear
     * or a full engine-level VRAM manager (to reuse space for another node) -
     * a separate next step at the scene loader level, not in this file specifically */
}

static const node_property_t sprite2d_properties[] = {
    { "Position X",  NODE_PROPERTY_TYPE_FLOAT,  { .f = 0.0f }, 0 },
    { "Position Y",  NODE_PROPERTY_TYPE_FLOAT,  { .f = 0.0f }, 0 },
    { "Rotation",    NODE_PROPERTY_TYPE_FLOAT,  { .f = 0.0f }, 0 },
    { "Scale X",     NODE_PROPERTY_TYPE_FLOAT,  { .f = 1.0f }, 0 },
    { "Scale Y",     NODE_PROPERTY_TYPE_FLOAT,  { .f = 1.0f }, 0 },
    { "Image Path",  NODE_PROPERTY_TYPE_STRING, { .s = "" },   1 },
    { "Raw Width",   NODE_PROPERTY_TYPE_INT,    { .i = 0 },     0 },
    { "Raw Height",  NODE_PROPERTY_TYPE_INT,    { .i = 0 },     0 },
    { "Raw Format",  NODE_PROPERTY_TYPE_INT,    { .i = 0 },     0 }
};

/* Exact byte offsets of each property in sprite2d_instance_t memory - in the
 * exact same order as sprite2d_properties above */
static const size_t sprite2d_property_offsets[] = {
    offsetof(sprite2d_instance_t, position_x),
    offsetof(sprite2d_instance_t, position_y),
    offsetof(sprite2d_instance_t, rotation),
    offsetof(sprite2d_instance_t, scale_x),
    offsetof(sprite2d_instance_t, scale_y),
    offsetof(sprite2d_instance_t, image_path),
    offsetof(sprite2d_instance_t, raw_width),
    offsetof(sprite2d_instance_t, raw_height),
    offsetof(sprite2d_instance_t, raw_format)
};

const node_interface_t sprite2d_interface = {
    sprite2d_init,
    sprite2d_update,
    sprite2d_draw,
    sprite2d_destroy,
    sprite2d_properties,
    sizeof(sprite2d_properties) / sizeof(sprite2d_properties[0]),
    sizeof(sprite2d_instance_t),
    sprite2d_property_offsets
};

/* @NODE type=NODE_TYPE_SPRITE_2D name=Sprite2D icon=sprite2d properties=sprite2d_properties */
/* The declaration above is the sole source that defines Sprite2D to the editor -
 * it must remain the last line in the file. */
