/* Deterministic native PS2 Makefile generation for generated and project C/C++ sources. */
#include <stdio.h>
#include <string.h>
#include <dirent.h>
#include <stdlib.h>
#include <sys/stat.h>
#include "export_internal.h"

#define MAX_EXPORT_SOURCES 1024

typedef struct {
    char path[1024];
    int is_cpp;
} export_source_name_t;

static int has_suffix(const char *name, const char *suffix) {
    size_t n = strlen(name), s = strlen(suffix);
    return n >= s && strcmp(name + n - s, suffix) == 0;
}

static int is_compile_source(const char *name, int *is_cpp) {
    if (has_suffix(name, ".c")) { if (is_cpp) *is_cpp = 0; return 1; }
    if (has_suffix(name, ".cc") || has_suffix(name, ".cpp") || has_suffix(name, ".cxx")) {
        if (is_cpp) *is_cpp = 1;
        return 1;
    }
    return 0;
}

static void add_source(export_source_name_t *sources, int *count,
                       const char *relative, int is_cpp) {
    if (*count >= MAX_EXPORT_SOURCES) return;
    for (int i = 0; i < *count; i++) {
        if (strcmp(sources[i].path, relative) == 0) return;
    }
    strncpy(sources[*count].path, relative, sizeof(sources[*count].path) - 1);
    sources[*count].path[sizeof(sources[*count].path) - 1] = '\0';
    sources[*count].is_cpp = is_cpp;
    (*count)++;
}

static void collect_sources(const char *root, const char *relative,
                            export_source_name_t *sources, int *count) {
    char directory[1600];
    snprintf(directory, sizeof(directory), "%s%s%s", root,
             relative[0] ? "/" : "", relative);
    DIR *dir = opendir(directory);
    if (dir == NULL) return;
    char names[512][256];
    int name_count = 0;
    struct dirent *entry;
    while ((entry = readdir(dir)) != NULL && name_count < 512) {
        if (strcmp(entry->d_name, ".") == 0 || strcmp(entry->d_name, "..") == 0) continue;
        strncpy(names[name_count], entry->d_name, sizeof(names[name_count]) - 1);
        names[name_count][sizeof(names[name_count]) - 1] = '\0';
        name_count++;
    }
    closedir(dir);
    for (int i = 1; i < name_count; i++) {
        char key[256];
        memcpy(key, names[i], sizeof(key));
        int j = i;
        while (j > 0 && strcmp(key, names[j - 1]) < 0) {
            memcpy(names[j], names[j - 1], sizeof(names[j]));
            j--;
        }
        memcpy(names[j], key, sizeof(names[j]));
    }
    for (int i = 0; i < name_count; i++) {
        char child_relative[1200];
        snprintf(child_relative, sizeof(child_relative), "%s%s%s", relative,
                 relative[0] ? "/" : "", names[i]);
        char full_path[1800];
        snprintf(full_path, sizeof(full_path), "%s/%s", root, child_relative);
        struct stat st;
        if (stat(full_path, &st) != 0) continue;
        if (S_ISDIR(st.st_mode)) {
            if (strcmp(names[i], ".git") == 0 || strcmp(names[i], ".svn") == 0 ||
                strcmp(names[i], "build") == 0 || strcmp(names[i], "Temp") == 0) continue;
            collect_sources(root, child_relative, sources, count);
        } else {
            int is_cpp = 0;
            if (S_ISREG(st.st_mode) && is_compile_source(names[i], &is_cpp)) {
                add_source(sources, count, child_relative, is_cpp);
            }
        }
    }
}

void export_makefile_write(const char *build_dir, const char *src_dir_name) {
    char path[1300];
    snprintf(path, sizeof(path), "%s/Makefile", build_dir);
    FILE *f = fopen(path, "w");
    if (f == NULL) return;

    export_source_name_t sources[MAX_EXPORT_SOURCES];
    int source_count = 0;
    collect_sources(build_dir, "", sources, &source_count);
    int has_cpp = 0;
    for (int i = 0; i < source_count; i++) if (sources[i].is_cpp) has_cpp = 1;

    fprintf(f, "# Generated by Rebax - native PS2 project Makefile.\n\n");
    fprintf(f, "EE_BIN = %s.elf\n", g_exe_name);
    fprintf(f, "EE_HAS_CXX := %d\n", has_cpp);
    fprintf(f, "EE_OBJS =");
    for (int i = 0; i < source_count; i++) {
        char object[1024];
        strncpy(object, sources[i].path, sizeof(object) - 1);
        object[sizeof(object) - 1] = '\0';
        char *dot = strrchr(object, '.');
        if (dot != NULL) strcpy(dot, ".o");
        fprintf(f, " %s", object);
    }
    fprintf(f, "\n\n");

    fprintf(f, "EE_INCS := -I%s -Iproject\n", src_dir_name);
    for (int i = 0; i < g_extra_incs_count; i++) fprintf(f, "EE_INCS += %s\n", g_extra_incs[i]);
    fprintf(f, "EE_LIBS := -Wl,--start-group\n");
    for (int i = 0; i < g_extra_libs_count; i++) fprintf(f, "EE_LIBS += %s\n", g_extra_libs[i]);
    fprintf(f, "EE_LIBS += -Wl,--end-group\n\n");
    fprintf(f, ".DEFAULT_GOAL := all\n\n");
    if (g_is_release) {
        fprintf(f, "all: $(EE_BIN)\n\t$(EE_STRIP) --strip-all $(EE_BIN)\n\n");
    } else {
        fprintf(f, "all: $(EE_BIN)\n\n");
    }
    fprintf(f, "include $(PS2SDK)/samples/Makefile.pref\n");
    if (has_cpp) fprintf(f, "include $(PS2SDK)/samples/Makefile.eeglobal_cpp\n");
    else fprintf(f, "include $(PS2SDK)/samples/Makefile.eeglobal\n");
    fclose(f);
}
